# Generated by Django 4.2.4 on 2025-01-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_alojamiento', models.CharField(choices=[('Tienda', 'Tienda'), ('Cabaña', 'Cabaña'), ('Caravana', 'Caravana')], max_length=20)),
                ('numero_personas', models.PositiveIntegerField()),
                ('estado_reserva', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campamento.campista')),
            ],
        ),
    ]
